# Generated by Django 5.0.6 on 2024-06-06 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "Order_ID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Username", models.CharField(max_length=255)),
                ("Products", models.CharField(max_length=255)),
                ("Purchase_amount", models.IntegerField()),
                ("Type", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255, unique=True)),
                ("Price", models.PositiveIntegerField()),
                ("suger", models.PositiveIntegerField()),
                ("coffee", models.PositiveIntegerField()),
                ("flour", models.PositiveIntegerField()),
                ("chocolate", models.PositiveIntegerField()),
                ("vertical", models.BinaryField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="storage",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255, unique=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0, "error")
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users_Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders_Product",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "orders_orderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CoffeeSite.orders",
                    ),
                ),
                (
                    "prodect_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CoffeeSite.products",
                    ),
                ),
            ],
        ),
    ]
