# Generated by Django 5.0.6 on 2024-06-07 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CoffeeSite", "0003_alter_users_orders_orders_orderid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="Order_ID",
            new_name="order_id",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="Products",
            new_name="products",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="Purchase_amount",
            new_name="purchase_amount",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="Type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="Username",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="orders_product",
            old_name="ID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="orders_product",
            old_name="orders_orderid",
            new_name="order_id",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="ID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="storage",
            old_name="ID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="storage",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="users_orders",
            old_name="Orders_orderID",
            new_name="orderID",
        ),
        migrations.RenameField(
            model_name="users_orders",
            old_name="Users_username",
            new_name="username",
        ),
        migrations.AlterUniqueTogether(
            name="users_orders",
            unique_together={("username", "orderID")},
        ),
    ]
