# Generated by Django 5.0.6 on 2024-06-07 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CoffeeSite", "0004_rename_order_id_orders_order_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="products",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="orders_product",
            old_name="prodect_id",
            new_name="product_id",
        ),
    ]
