# Generated by Django 5.0.6 on 2024-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeSite', '0006_alter_products_vertical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='type',
            new_name='is_takeout',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='purchase_amount',
        ),
        migrations.AddField(
            model_name='orders_product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Users_Orders',
        ),
    ]
