# Generated by Django 5.0.6 on 2024-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CoffeeSite",
            "0007_rename_type_orders_is_takeout_remove_orders_product_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="coffee",
            new_name="raw_coffee",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="suger",
            new_name="sugar",
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(null=True, upload_to="products/"),
        ),
    ]
