# Generated by Django 5.0.6 on 2024-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CoffeeSite", "0008_rename_coffee_products_raw_coffee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="date",
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.URLField(),
        ),
    ]
