# Generated by Django 5.0.6 on 2024-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CoffeeSite", "0009_orders_date_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateField(auto_created=True, default="01/01"),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name="products",
            name="vertical",
            field=models.CharField(
                choices=[
                    ("warm_drink", "نوشیدنی گرم"),
                    ("cold_drink", "نوشیدنی سرد"),
                    ("cake", "کیک"),
                ],
                max_length=50,
            ),
        ),
    ]
