# Generated by Django 5.0.6 on 2024-06-27 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CoffeeSite", "0011_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateField(
                auto_created=True, default=datetime.date(2024, 6, 27)
            ),
        ),
    ]
