# Generated by Django 5.0.6 on 2024-06-27 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CoffeeSite", "0012_alter_orders_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
    ]
