# Generated by Django 5.0.6 on 2024-06-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeSite', '0012_alter_products_image'),
        ('CoffeeSite', '0013_alter_orders_date'),
    ]

    operations = [
    ]
