# Generated by Django 5.0.6 on 2024-06-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeSite', '0014_merge_20240629_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='CoffeeSite/media/products'),
        ),
    ]
